import oracledb   

def create_tables():
    conn = oracledb.connect(
        user="system",
        password="shardul",
        dsn = "localhost:1521/FREE"
    )
    cur = conn.cursor()

    # Create policyholders table
    cur.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE TABLE policyholders (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(100),
                age NUMBER,
                policy_type VARCHAR2(20),
                sum_insured NUMBER
            )
        ';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN -- ORA-00955: name is already used by an existing object
                RAISE;
            END IF;
    END;
    """)

    # Create claims table
    cur.execute("""
    BEGIN
        EXECUTE IMMEDIATE '
            CREATE TABLE claims (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                policyholder_id NUMBER REFERENCES policyholders(id),
                amount NUMBER,
                reason VARCHAR2(255),
                status VARCHAR2(20),
                date_of_claim DATE
            )
        ';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    """)

    conn.commit()
    cur.close()
    conn.close()
    print("Tables created.")

if __name__ == "__main__":
    create_tables()

    